### ISSUE TITLE
issue with  Mautic 5.0.2

### ISSUE THREAD

**Issue by nezam05** [rcarabelli/Mautic-Zender-Plugin#17]
hi, when trying to clear cache, I got this with Mautic 5.0.2

```
In ZenderIntegration.php line 71:
                                                                                                                                                                         
  Compile Error: Declaration of MauticPlugin\MauticZenderBundle\Integration\ZenderIntegration::getFormSettings() must be compatible with Mautic\PluginBundle\Integration\AbstractIntegration::getFormSettings(): array  
```

can you please fix this?

**Comment by rcarabelli** [comment]
We are not working currently with Mautic 5, we are still at 4
Our migration will happen in May, by then we will address this issue.
If possible we will try to solve this before.

**Comment by rcarabelli** [comment]
The new release working on Mautic v. 5.1.0: https://github.com/rcarabelli/Mautic-Zender-Plugin/releases/tag/v.1.1.0

Let me know if you find any issues please.

**Comment by rcarabelli** [comment]
Updated the code for Mautic 5.1
